apiVersion: redhatcop.redhat.io/v1alpha1
kind: GitHubAuthEngineConfig
metadata:
  labels:
    app.kubernetes.io/name: githubauthengineconfig
    app.kubernetes.io/instance: githubauthengineconfig-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: githubauthengineconfig-sample
spec:
  # TODO(user): Add fields here
